#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# Sentinel installer
# ─────────────────────────────────────────────────────────────────────────────
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kuldeep-poonia/terminal-log-highlighter/main/install.sh | bash
#
# What this script does:
#   1. Downloads the pre-built sentinel binary for your OS/arch.
#   2. Installs it to /usr/local/bin/sentinel.
#   3. Writes ~/.sentinel_shell.sh with shell wrapper functions that
#      transparently route docker, npm, cargo, etc. through sentinel.
#   4. Sources that file from ~/.bashrc and ~/.zshrc so the integration
#      is active in every new terminal session.
#
# After running this script, restart your terminal (or source your rc file).
# From that point on, sentinel is completely invisible – you run your commands
# exactly as before, and any error or warning line is highlighted automatically.
# ─────────────────────────────────────────────────────────────────────────────
set -e

GITHUB_REPO="kuldeep-poonia/terminal-log-highlighter"
BINARY_NAME="sentinel"
INSTALL_DIR="/usr/local/bin"
SHELL_FILE="$HOME/.sentinel_shell.sh"

# ── 1. Detect OS and architecture ────────────────────────────────────────────
OS=$(uname -s)
ARCH=$(uname -m)

case "$OS" in
    Linux)  OS="Linux"  ;;
    Darwin) OS="Darwin" ;;
    *)      echo "✗ Unsupported operating system: $OS"; exit 1 ;;
esac

case "$ARCH" in
    x86_64)        ARCH="x86_64" ;;
    aarch64|arm64) ARCH="arm64"  ;;
    *)             echo "✗ Unsupported architecture: $ARCH"; exit 1 ;;
esac

# ── 2. Download binary ────────────────────────────────────────────────────────
DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/latest/download/${BINARY_NAME}-${OS}-${ARCH}"

echo ""
echo "  ⬇  Downloading sentinel for ${OS}-${ARCH} ..."
curl -fsSL --progress-bar "$DOWNLOAD_URL" -o "/tmp/${BINARY_NAME}"
chmod +x "/tmp/${BINARY_NAME}"

# ── 3. Install binary ─────────────────────────────────────────────────────────
echo "  📦 Installing to ${INSTALL_DIR}/${BINARY_NAME} ..."
sudo mv "/tmp/${BINARY_NAME}" "${INSTALL_DIR}/${BINARY_NAME}"

# ── 4. Write shell integration file ──────────────────────────────────────────
echo "  🔧 Writing shell integration to ${SHELL_FILE} ..."

cat > "$SHELL_FILE" << 'END_SHELL'
# ─────────────────────────────────────────────────────────────────────────────
# Sentinel shell integration  —  ~/.sentinel_shell.sh
# Auto-generated by the sentinel installer.
# ─────────────────────────────────────────────────────────────────────────────
#
# Each function below wraps a common dev-tool command so that sentinel sits
# invisibly between you and the tool.  Sentinel spawns the real command inside
# a PTY so the tool still believes it has a real terminal:
#   • Colour output is preserved (Docker Compose service colours, etc.)
#   • Window size is passed correctly (progress bars, line wrapping)
#   • Ctrl+C / Ctrl+D / interactive stdin work as normal
#   • The exit code of the real command is forwarded unchanged
#
# To DISABLE a wrapper: remove or comment out the relevant line below and
# reload your shell (`source ~/.bashrc` / `source ~/.zshrc`).
#
# To UNWRAP a command temporarily:
#   command docker compose up --build     # bypasses the sentinel wrapper
# ─────────────────────────────────────────────────────────────────────────────

# Internal helper – only wraps when sentinel is installed.
_sentinel_run() {
    if command -v sentinel >/dev/null 2>&1; then
        sentinel "$@"
    else
        command "$@"
    fi
}

# ── Wrappers ──────────────────────────────────────────────────────────────────
# Docker / container tooling
docker()     { _sentinel_run docker    "$@"; }
podman()     { _sentinel_run podman    "$@"; }
kubectl()    { _sentinel_run kubectl   "$@"; }
helm()       { _sentinel_run helm      "$@"; }

# Node.js ecosystem
npm()        { _sentinel_run npm       "$@"; }
yarn()       { _sentinel_run yarn      "$@"; }
pnpm()       { _sentinel_run pnpm      "$@"; }
bun()        { _sentinel_run bun       "$@"; }
node()       { _sentinel_run node      "$@"; }

# Rust
cargo()      { _sentinel_run cargo     "$@"; }

# Build systems
make()       { _sentinel_run make      "$@"; }
cmake()      { _sentinel_run cmake     "$@"; }
gradle()     { _sentinel_run gradle    "$@"; }
mvn()        { _sentinel_run mvn       "$@"; }

# Python
python()     { _sentinel_run python    "$@"; }
python3()    { _sentinel_run python3   "$@"; }
pytest()     { _sentinel_run pytest    "$@"; }
pip()        { _sentinel_run pip       "$@"; }
pip3()       { _sentinel_run pip3      "$@"; }

# Go
go()         { _sentinel_run go        "$@"; }

# Ruby
bundle()     { _sentinel_run bundle    "$@"; }
rails()      { _sentinel_run rails     "$@"; }

# Java / Kotlin
java()       { _sentinel_run java      "$@"; }
kotlin()     { _sentinel_run kotlin    "$@"; }
END_SHELL

# ── 5. Source shell integration from rc files ─────────────────────────────────
SENTINEL_SOURCE='[ -f "$HOME/.sentinel_shell.sh" ] && source "$HOME/.sentinel_shell.sh"'
SENTINEL_MARKER='sentinel_shell'   # used to detect if line is already present

_add_to_rc() {
    local rc="$1"
    if [ -f "$rc" ]; then
        if ! grep -qF "$SENTINEL_MARKER" "$rc" 2>/dev/null; then
            printf '\n# Sentinel log highlighter\n%s\n' "$SENTINEL_SOURCE" >> "$rc"
            echo "     ✅ Added to $rc"
        else
            echo "     ↩  Already in $rc – skipped"
        fi
    fi
}

echo "  🔗 Hooking into shell rc files ..."
_add_to_rc "$HOME/.bashrc"
_add_to_rc "$HOME/.zshrc"
_add_to_rc "$HOME/.bash_profile"   # macOS bash login shells

# ── 6. Verify ─────────────────────────────────────────────────────────────────
echo ""
if command -v sentinel &>/dev/null; then
    SENTINEL_VERSION=$(sentinel --version 2>/dev/null || echo "installed")
    echo "  ✅ Sentinel ${SENTINEL_VERSION} is ready."
    echo ""
    echo "  ┌─ Next step ────────────────────────────────────────────────────┐"
    echo "  │  Restart your terminal, or run:                               │"
    echo "  │                                                                │"
    echo "  │    source ~/.bashrc          # bash users                     │"
    echo "  │    source ~/.zshrc           # zsh users                      │"
    echo "  │                                                                │"
    echo "  │  Then use your tools exactly as before – sentinel is silent   │"
    echo "  │  until it detects an error or warning.                        │"
    echo "  │                                                                │"
    echo "  │  Examples (these commands are unchanged):                      │"
    echo "  │    docker compose up --build                                   │"
    echo "  │    npm run start                                               │"
    echo "  │    cargo build                                                 │"
    echo "  │    kubectl apply -f deployment.yaml                            │"
    echo "  │                                                                │"
    echo "  │  Custom patterns:  cp .sentinel.toml ~/.sentinel.toml          │"
    echo "  │  Disable wrapper:  edit ~/.sentinel_shell.sh                  │"
    echo "  └────────────────────────────────────────────────────────────────┘"
    echo ""
else
    echo "  ⚠️  Binary installed but 'sentinel' not found in PATH."
    echo "     Check that ${INSTALL_DIR} is in your PATH."
fi